### ISSUE TITLE
Task :react-native-dualscreeninfo:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by rhalaly** [microsoft/react-native-dualscreen#141]
When I add `react-native-dualscreeninfo` to my project:
```
  "dependencies": {
    ...
    "react-native-dualscreeninfo": "^0.3.2"
  },
```

The React Native fails to start:
```
> Task :react-native-dualscreeninfo:compileDebugKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/***/.gradle/caches/transforms-3/0cc2c87c50a91c241657c7bbcc18eaa9/transformed/jetified-kotlin-stdlib-jdk8-1.6.10.jar (version 1.6)
    C:/***/.gradle/caches/transforms-3/0ef692519a16046a76835cdd74636faf/transformed/jetified-kotlin-stdlib-jdk7-1.3.72.jar (version 1.3)
    C:/***/.gradle/caches/transforms-3/f713c139f4c7914776c902517e455c4f/transformed/jetified-kotlin-stdlib-1.3.72.jar (version 1.3)
    C:/***/.gradle/caches/transforms-3/5beb6206e8cf9cbeaeb2b3682ce09f72/transformed/jetified-kotlin-stdlib-common-1.3.72.jar (version 1.3)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
62 actionable tasks: 22 executed, 40 up-to-date
e: C:/***/.gradle/caches/transforms-3/0cc2c87c50a91c241657c7bbcc18eaa9/transformed/jetified-kotlin-stdlib-jdk8-1.6.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.16.
e: C:/***/.gradle/caches/transforms-3/6be88576f4b7b1961ac7d162e1cbe754/transformed/jetified-react-native-0.69.2-debug-api.jar!/META-INF/ReactAndroid_debug.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.16.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-dualscreeninfo:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
e: C:/***/.gradle/caches/transforms-3/0cc2c87c50a91c241657c7bbcc18eaa9/transformed/jetified-kotlin-stdlib-jdk8-1.6.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.16.
e: C:/***/.gradle/caches/transforms-3/6be88576f4b7b1961ac7d162e1cbe754/transformed/jetified-react-native-0.69.2-debug-api.jar!/META-INF/ReactAndroid_debug.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.16.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-dualscreeninfo:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (C:\***\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\***\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (C:\***\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\***\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ***@0.0.1 android: `react-native run-android --no-jetifier`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ***@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\***\AppData\Roaming\npm-cache\_logs\2022-07-23T15_30_29_247Z-debug.log
```

Any idea how to solve it?

**Comment by jonthysell** [comment]
@chrisglein Is there someone maintaining the Android build that can look at this?

**Comment by chrisglein** [comment]
> @chrisglein Is there someone maintaining the Android build that can look at this?

We don't have bandwidth to look into this right now.
@aDavidaIsNoOne has spent time with this module more recently. Aaron does this reproduce for you?

**Comment by shahidcodes** [comment]
anyone managed to solve this?

project fails to run after installing the library
```npm i react-native-dualscreeninfo```
